name: major_project
description: "Court Cases Scheduling Application"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  get: ^4.6.6
  firebase_messaging: ^15.2.2
  cloud_firestore: ^5.6.3
  firebase_database: ^11.3.2
  firebase_storage: ^12.4.2
  cunning_document_scanner: ^1.2.3
  google_mlkit_text_recognition: ^0.14.0
  uuid: ^4.5.1
  intl: ^0.20.2
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
